import type { Face, PositionCatalog } from "./types";

export const FACE_ORDER: Face[] = ["front", "back", "right", "left"];

export const TRIP = {
  window: "20 Sep – early Nov 2026",
  salesClose: "10 Oct 2026",
  artworkDays: 5,
  startPrice: 45,
  spotCount: 22,
} as const;

const FRONT = {
  x: 23.8,
  bannerW: 52.8,
  cellW: 25.7,
  rightX: 50.9,
  bannerY: 29.4,
  bannerH: 12.4,
  cellH: 13.9,
  rowsY: [43.0, 57.8, 72.6],
} as const;

const SIDE = {
  leftX: 33.8,
  rightX: 50.4,
  w: 16.0,
  topY: 29.6,
  bottomY: 61.2,
  h: 21.2,
} as const;

export const POSITION_CATALOG: PositionCatalog[] = [
  {
    id: 1,
    face: "front",
    price: 280,
    size: "40 × 15 cm",
    tier: "presenting",
    x: FRONT.x,
    y: FRONT.bannerY,
    width: FRONT.bannerW,
    height: FRONT.bannerH,
  },
  {
    id: 2,
    face: "front",
    price: 150,
    size: "17 × 12 cm",
    tier: "premium",
    x: FRONT.x,
    y: FRONT.rowsY[0],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 3,
    face: "front",
    price: 145,
    size: "17 × 12 cm",
    tier: "premium",
    x: FRONT.rightX,
    y: FRONT.rowsY[0],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 4,
    face: "front",
    price: 125,
    size: "17 × 12 cm",
    tier: "premium",
    x: FRONT.x,
    y: FRONT.rowsY[1],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 5,
    face: "front",
    price: 120,
    size: "17 × 12 cm",
    tier: "premium",
    x: FRONT.rightX,
    y: FRONT.rowsY[1],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 19,
    face: "front",
    price: 110,
    size: "17 × 12 cm",
    tier: "premium",
    x: FRONT.x,
    y: FRONT.rowsY[2],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 20,
    face: "front",
    price: 105,
    size: "17 × 12 cm",
    tier: "premium",
    x: FRONT.rightX,
    y: FRONT.rowsY[2],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 6,
    face: "back",
    price: 200,
    size: "40 × 15 cm",
    tier: "premium",
    x: FRONT.x,
    y: FRONT.bannerY,
    width: FRONT.bannerW,
    height: FRONT.bannerH,
  },
  {
    id: 7,
    face: "back",
    price: 95,
    size: "17 × 12 cm",
    tier: "mid",
    x: FRONT.x,
    y: FRONT.rowsY[0],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 8,
    face: "back",
    price: 90,
    size: "17 × 12 cm",
    tier: "mid",
    x: FRONT.rightX,
    y: FRONT.rowsY[0],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 9,
    face: "back",
    price: 85,
    size: "17 × 12 cm",
    tier: "mid",
    x: FRONT.x,
    y: FRONT.rowsY[1],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 10,
    face: "back",
    price: 75,
    size: "17 × 12 cm",
    tier: "mid",
    x: FRONT.rightX,
    y: FRONT.rowsY[1],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 21,
    face: "back",
    price: 70,
    size: "17 × 12 cm",
    tier: "mid",
    x: FRONT.x,
    y: FRONT.rowsY[2],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 22,
    face: "back",
    price: 60,
    size: "17 × 12 cm",
    tier: "mid",
    x: FRONT.rightX,
    y: FRONT.rowsY[2],
    width: FRONT.cellW,
    height: FRONT.cellH,
  },
  {
    id: 11,
    face: "left",
    price: 65,
    size: "10 × 10 cm",
    tier: "side",
    x: SIDE.leftX,
    y: SIDE.topY,
    width: SIDE.w,
    height: SIDE.h,
  },
  {
    id: 12,
    face: "left",
    price: 55,
    size: "10 × 10 cm",
    tier: "side",
    x: SIDE.rightX,
    y: SIDE.topY,
    width: SIDE.w,
    height: SIDE.h,
  },
  {
    id: 13,
    face: "left",
    price: 50,
    size: "10 × 10 cm",
    tier: "side",
    x: SIDE.leftX,
    y: SIDE.bottomY,
    width: SIDE.w,
    height: SIDE.h,
  },
  {
    id: 14,
    face: "left",
    price: 45,
    size: "10 × 10 cm",
    tier: "side",
    x: SIDE.rightX,
    y: SIDE.bottomY,
    width: SIDE.w,
    height: SIDE.h,
  },
  {
    id: 15,
    face: "right",
    price: 65,
    size: "10 × 10 cm",
    tier: "side",
    x: SIDE.leftX,
    y: SIDE.topY,
    width: SIDE.w,
    height: SIDE.h,
  },
  {
    id: 16,
    face: "right",
    price: 55,
    size: "10 × 10 cm",
    tier: "side",
    x: SIDE.rightX,
    y: SIDE.topY,
    width: SIDE.w,
    height: SIDE.h,
  },
  {
    id: 17,
    face: "right",
    price: 50,
    size: "10 × 10 cm",
    tier: "side",
    x: SIDE.leftX,
    y: SIDE.bottomY,
    width: SIDE.w,
    height: SIDE.h,
  },
  {
    id: 18,
    face: "right",
    price: 45,
    size: "10 × 10 cm",
    tier: "side",
    x: SIDE.rightX,
    y: SIDE.bottomY,
    width: SIDE.w,
    height: SIDE.h,
  },
];

export function padSpot(id: number) {
  return String(id).padStart(2, "0");
}

export function getCatalogById(id: number) {
  return POSITION_CATALOG.find((position) => position.id === id);
}

export function artworkSpec(size: string) {
  const match = /(\d+)\s*[×x]\s*(\d+)/i.exec(size);
  const cmW = match ? Number(match[1]) : 17;
  const cmH = match ? Number(match[2]) : 12;
  const pxW = Math.round((cmW / 2.54) * 300 / 50) * 50;
  const pxH = Math.round((cmH / 2.54) * 300 / 50) * 50;
  return {
    cmW,
    cmH,
    pxW,
    pxH,
    sizeLabel: `${cmW} × ${cmH} cm`,
    pixelLabel: `${pxW} × ${pxH} px`,
  };
}
